### ISSUE TITLE
Can t loggin with google

### ISSUE THREAD

**Issue by ranouf** [auth0-samples/auth0-aspnetcore-mvc-samples#22]
I downloaded the app from:
https://auth0.com/docs/quickstart/webapp/aspnet-core/02-login-custom

My Google Settings are correctly configured in the Auth 0 Dashboard Settings

this is the error i have after google login:
SecurityTokenInvalidSignatureException: IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: XXFCNkFBRDAyMUY2ODZBQjEwOEMxNUJBQzM3M0NCNUFFNkY4OTFDNg
Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: XXFCNkFBRDAyMUY2ODZBQjEwOEMxNUJBQzM3M0NCNUFFNkY4OTFDNg
'.
Exceptions caught:
''.
token: '{"alg":"HS256","typ":"JWT"}.{"iss":"https://XXXXX.auth0.com/","sub":"google-oauth2|114777821239011062790","aud":"2162e942jcrTHgcTFD9BRqIwpzdQhxzQ","exp":1494393833,"iat":1494357833,"nonce":"XX6299546302340106.N2EzN2EzZTQtN2QzNi00OTUzLTljNzQtMmJlZGIxMTgwYjFkMGNkNmExY2UtNDZmMi00MTUwLWExYTktNWFlNzEwODQwZWQ1"}'.
System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(string token, TokenValidationParameters validationParameters)

AggregateException: Unhandled remote failure. (IDX10503: Signature validation failed. Keys tried: 'Microsoft.IdentityModel.Tokens.X509SecurityKey , KeyId: XXFCNkFBRDAyMUY2ODZBQjEwOEMxNUJBQzM3M0NCNUFFNkY4OTFDNg
Microsoft.IdentityModel.Tokens.RsaSecurityKey , KeyId: XXFCNkFBRDAyMUY2ODZBQjEwOEMxNUJBQzM3M0NCNUFFNkY4OTFDNg
'.
Exceptions caught:
''.
token: '{"alg":"HS256","typ":"JWT"}.{"iss":"https://XX.auth0.com/","sub":"google-oauth2|114777821239011062790","aud":"2162e942jcrTHgcTFD9BRqIwpzdQhxzQ","exp":1494393833,"iat":1494357833,"nonce":"XX6299546302340106.N2EzN2EzZTQtN2QzNi00OTUzLTljNzQtMmJlZGIxMTgwYjFkMGNkNmExY2UtNDZmMi00MTUwLWExYTktNWFlNzEwODQwZWQ1"}'.)
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRemoteCallbackAsync>d__6.MoveNext()

Can you help me to fix it?

**Comment by jerriep** [comment]
Your OIDC middleware is configured to work with RS256 tokens, but your tokens are signed using HS256.

You have 2 options:

1. **Change your JWT Signature algorithm to RS256 (recommended)**. To do this go to your Client settings in the Auth0 Dashboard, click _Show Advanced Settings_, and go the _OAuth_ tab. Set _JsonWebToken Signature Algorithm_ to **RS256**. Save your settings.

2. **Change your OIDC middleware configuration**. For that you can look at the code in this sample: https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/tree/master/Samples/oidc-hs256. In particular, [this line](https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/blob/master/Samples/oidc-hs256/Startup.cs#L81), and [these lines](https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/blob/master/Samples/oidc-hs256/Startup.cs#L138-L141)

If you have further issues I want to ask you to please work through the proper support channels. For that you can go to https://support.auth0.com/

**Comment by ranouf** [comment]
Yes, you are true! Thank for your response :)
