### ISSUE TITLE
Overriding The Name ClaimType

### ISSUE THREAD

**Issue by Haleni888** [auth0-samples/auth0-aspnetcore-mvc-samples#23]
Referring to the [User Profile Quick Start](https://auth0.com/docs/quickstart/webapp/aspnet-core/04-user-profile),
It is possible to override the default Name ClaimType of .net core security claims (http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name) so that _User.Identity.Name_ will retrieve name claim without the need to add this claim in the _Ticket Received_ event:

`var options = new OpenIdConnectOptions("Auth0")
{`
&nbsp;&nbsp;&nbsp;&nbsp;`[...] // omitted for brevity`
&nbsp;&nbsp;&nbsp;&nbsp;`TokenValidationParameters = new TokenValidationParameters() { NameClaimType = "name" }`
`};`

The Profile action in the Account Controller should be changed to:

`return View(new UserProfileViewModel()
{`
&nbsp;&nbsp;&nbsp;&nbsp;`Name = User.Claims.FirstOrDefault(c => c.Type == "name")?.Value,`
&nbsp;&nbsp;&nbsp;&nbsp;`EmailAddress = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value,`
&nbsp;&nbsp;&nbsp;&nbsp;`ProfileImage = User.Claims.FirstOrDefault(c => c.Type == "picture")?.Value`
`});`

**Comment by jerriep** [comment]
Thank you for notifying me of this @Haleni888 !

I will look into this and update our quickstarts and sample applications appropriately :)
