### ISSUE TITLE
Where is the User data stored after a successful login?

### ISSUE THREAD

**Issue by decapo01** [auth0-samples/auth0-aspnetcore-mvc-samples#24]
This is more of a question than an issue.

Sorry for my ignorance, I've completed the cutsom login sample and it works fine.  However with I check for session data I don't see anything.  I have my session set up with redis and there is also not anything in redis.  Where is this user data stored after a successfull login?  I updated the SaveTokens to true and I still don't see anything in my session data.

**Comment by jerriep** [comment]
The user information is stored in a cookie. I do not believe anything is stored is session information on the server, unless you specifically do this.

Not sure whether the actual tokens are also stored in the cookie, as I have not tested this.

**Comment by decapo01** [comment]
I just learned a bit more about json web tokens.  It appears the server just has the secret key that is used to verify the signature of the token that is sent in the http request.  The server uses the secret key to determine if the token sent is authentic.  You could just store all the information about the user in the token and I think there appears to be no need for session data unless you really want it.  I have another question.  In a situation where you have multiple application servers behind a load balancer, should everything work the same as long as all the application servers have the same secret key?

**Comment by jerriep** [comment]
I am a bit confused as to what sort of application you are building. From your first question it sounds like you are building a web application, but then on the second one you talk about a token being sent in the HTTP request - which makes me think you are talking about an API because in that case the token (JWT) gets sent with each request.

Can you please clarify what exactly you are talking about, because a normal MVC web app vs a Web API operate quite differently

**Comment by decapo01** [comment]
It is a normal MVC app.  I'm going through the get started part now and this is how I believed authentication is working.  After login a cookie is created and sent to the browser.  The cookie in the browser is a JWT and is sent to the MVC application on every request.  The application uses it's secret key to decode the JWT to authenticate it.  One can store data in the JWT instead of in a session on the server side.  Is this not the way it works?

**Comment by jerriep** [comment]
The data in the cookie is not a JWT (to my knowledge).

What happens is that the OIDC middleware authenticates the user with Auth0. Auth0 will return the user information inside an `id_token` - which is a JWT. The OIDC middleware will then take the claims inside the `id_token` and creates a [ClaimsPrincipal](https://msdn.microsoft.com/en-us/library/system.security.claims.claimsprincipal(v=vs.110).aspx) containing the claims from the `id_token`.

The information for the User (i.e. the `ClaimsPrincipal`) is then stored in a cookie. 

You can add extra information to the user by adding extra claims to the `ClaimsPrincipal`.

You can also store extra session information using the standard session related information.

But, AFAIK the cookie for authentication, and the session information are 2 separate things.

I suggest you read the Security section in the ASP.NET Core docs:
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/

Also read about storing application state:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/app-state

I also strongly suggest you work through this ASP.NET Authorization Workshop
https://github.com/blowdart/AspNetAuthorizationWorkshop

At the end of the day Auth0 simply sits on top of the standard ASP.NET Security mechanisms. If you need more in-depth information on that I suggest you raise it with the ASP.NET Core team or ask those questions on the appropriate forums
