### ISSUE TITLE
Authentication cookie settings in samples are insecure

### ISSUE THREAD

**Issue by openidauthority** [auth0-samples/auth0-aspnetcore-mvc-samples#26]
The settings for the CookieAuthentication middleware are fine for demo purposes, but in the real world would make applications susceptible to cookie theft and session hijacking. Developers use these samples as a guide for configuring real applications, so it would be good to include a note or warning. Perhaps something along these lines would work:
```
// Add the cookie middleware
app.UseCookieAuthentication(new CookieAuthenticationOptions
{
    AutomaticAuthenticate = true,
    AutomaticChallenge = true,
    CookieHttpOnly = true,
    // When https is enabled, add CookieSecure = CookieSecurePolicy.Always,
});
```

**Comment by jerriep** [comment]
@openidauthority By default `CookieHttpOnly` is set to `true`

As for `CookieSecure`, the default samples are not configured for HTTPS, so this is not really relevant - unless ofcourse the developer goes an enables HTTPS for the website. But I am assuming that in this case they will go through the process of configuring the cookies correctly as well.

I do understand your concern, but once we start defining best secure practices, we can go on forever, and I do not think this is in the scope of our quickstarts.

If you do know of an external website with a checklist addressing these concerns I will be happy to link to it from the samples.

**Comment by jerriep** [comment]
Closing this issue. If you have any more feedback to give on this feel free to comment
