### ISSUE TITLE
InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found.

### ISSUE THREAD

**Issue by nicky-iliev** [auth0-samples/auth0-aspnetcore-mvc-samples#29]
Thank you for the great ASP.NET MVC sample using the latest .net core framework netcoreapp2

However, I see an issue when running the silent-auth sample. When I try to access the [site]/account/claims there is an exception "InvalidOperationException: No authenticationScheme was specified, and there was no DefaultChallengeScheme found."

Please note I am not logged in.

**Comment by kinetiq** [comment]
This helped me in my ASP.NET Core 2 project... However, after I make this change I get new errors when I use the login/logout methods on the quickstart account controller.

**For login I get:** 

InvalidOperationException: No authentication handler is configured to handle the scheme: Auth0

It is failing on this line: 

`await HttpContext.ChallengeAsync("Auth0", new AuthenticationProperties() { RedirectUri = returnUrl });`

**For logout I get:**

No IAuthenticationSignOutHandler is configured to handle sign out for the scheme: Auth0

```
And that one is failing on this line:

            await HttpContext.SignOutAsync("Auth0", new AuthenticationProperties
            {
                // Indicate here where Auth0 should redirect the user after a logout.
                // Note that the resulting absolute Uri must be whitelisted in the 
                // **Allowed Logout URLs** settings for the client.
                RedirectUri = Url.Action("Index", "Home")
            });
```

Please help... Thanks!

**Comment by jerriep** [comment]
Did you specify "Auth0" as the authentication scheme when registering the OIDC middleware?

https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/blob/22acfe8f788e53ba7c54897881094deef45765f4/Quickstart/01-Login/SampleMvcApp/Startup.cs#L35

**Comment by kinetiq** [comment]
Hey Jerrie, I figured this out. My problem was that one of the schemes at the top used OpenIdAuthenticationDefaults instead of Cookie... I am not sure how that happened. Thanks!
