### ISSUE TITLE
WebApp ASP.net Core: Security Warning received from firefox browser.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-aspnetcore-mvc-samples#32]
After click in the "LOG IN" button, using firefox browser, a security warning is received.

![image](https://user-images.githubusercontent.com/26749061/33382801-1620d74a-d4f8-11e7-81ea-655e004823a2.png)

Firefox version:

![image](https://user-images.githubusercontent.com/26749061/33382832-25f650b4-d4f8-11e7-924d-4335c26bf563.png)

**Comment by jerriep** [comment]
@HeikerAraujo Same as before.... Can you please be a bit more clear as to what sample app it is you were running? Or how you got this log in screen?

There are are many samples in this repository. I cannot help you if you are not specific about what sample it is you were running, and what the steps are you followed.

**Comment by jerriep** [comment]
No feedback from user. Closing issue
