### ISSUE TITLE
How can this be extended to user registration/sign up?

### ISSUE THREAD

**Issue by strich** [auth0-samples/auth0-aspnetcore-mvc-samples#33]
Whilst the samples provided a concise, I am unsure how to proceed in right a real world application that typically begins with user sign-up / registration, where they can supply application specific information. How does one begin to extend these examples?

**Comment by jerriep** [comment]
@strich The Lock widget, which is displayed for login in these samples, also act as a signup widget. So you use the exact flow in these samples for user sign-up. Maybe just change the link from **Login** to **Login / Sign Up**. 

Once the Lock widget displays, the user then has the option to click on the **Signup** tab of the Lock widget. To your application it is irrelevant whether the user has logged in or signed up as a new user - you will still get back the same details.

Unfortunately, if you need more in-depth guidance you will need to contact [Auth0 support](https://support.auth0.com/). As a contractor, I am responsible for these maintaining these samples, but with anything further, I cannot assist you. Auth0 has proper support structures in place to assist you with the questions you are asking.
