### ISSUE TITLE
Intermittent Correlation Failed Errors

### ISSUE THREAD

**Issue by kinetiq** [auth0-samples/auth0-aspnetcore-mvc-samples#35]
I am seeing intermittent Correlation Failed errors in production. The code we're using comes straight out of these  ASP.NET Core 2 quickstart samples.

For the most part, this happens in Chrome, although I also saw it in Safari once. To reproduce this, when I go to my site after several hours (maybe a whole day?) of inactivity, It shows the "you last logged in with..." dialog, and then when I click my email address, it crashes. 

Here's the trace, if that helps:

Exception: Correlation failed.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

I understand this issue may be cookie related, so I thought I would also include my cookies:

.AspNetCore.Correlation.Auth0.9vfQ2_WqWLP6U1UXAi29WBtXqsuo97f2txMiHCiovP0 | N
.AspNetCore.OpenIdConnect.Nonce.CfDJ8DczvQ50mOVLnddvitCTG7Kp9Mc2yKSennC7oggfuaXdypiCvst-PX2Hva-N9UxUe20wXELi1G6LHg8W_XHmCtbv9MN3lROrFKfrEaTf8MPue32mGPFLqMjiPIGJTuKlAxaC4r-kQMIHH1_MJzZV44mrQ5b1Jq8tPXgT0vZcAeC-QblWwgFWJN8PzdG0b2NOCog3p-0QQPVkuZr_D2v65roPEi-1nstgExcxlme_w_zzH98Fit3FcXKBPXq6TQY0oVfTHWpKLyPUj1dPg1WLCBc | N
ARRAffinity | 7055382eb098285fb6aecb1d7b22ab0e092973bf2838304a05303973781a3ebb

Please help, or point me towards the proper place to get assistance with this.

**Comment by jerriep** [comment]
@kinetiq I am not sure that I am in a position to sort this one out. It can be either in the ASP.NET Core middleware, or on the Auth0 authentication side - neither of which I have control over.

I have limited access to the Auth0 engineering teams, but I will ping them to see if this looks somehow familiar to them.

Will keep you updated...

**Comment by jerriep** [comment]
@kinetiq BTW, could you also please look through these and see if any of those describe your scenario?
https://github.com/aspnet/security/issues?utf8=%E2%9C%93&q=Correlation+Failed

**Comment by jerriep** [comment]
@kinetiq Sorry to do this to you, but I have been asked that you raise this issue through the proper support channels as you would be better supported there. Depending on your subscription, this means working either through the [Support Center](https://support.auth0.com/) or the [Auth0 Community](https://community.auth0.com/).

Still, my first suggestion would be to look through the issues on the ASP.NET repo I linked to above.

**Comment by kinetiq** [comment]
I haven't found anything in the Security repo that seems like the same thing, or perhaps I simply haven't peered deeply enough into the OIDC darkness. But I don't want to do that right now, I have very simple security needs. I suppose I have to consider trying to switch this project back to identity. I will try the support channels first. Thanks for trying.

**Comment by BrianVallelunga** [comment]
@kinetiq  I'm starting to get this too. Did you get a resolution?

**Comment by kinetiq** [comment]
@BrianVallelunga No resolution after two weeks. Not even a response! It seemed like @jerriep was interested in helping, but community support is giving me a really bad impression... Was going to recommend that we switch to a paid account, but if I can't get it to work, I'm afraid it will make me look bad. I will have no choice but to abandon Auth0 soon if I can't get help. 

You can see my thread here: https://community.auth0.com/t/asp-net-core-2-intermittent-correlation-failed-errors/11918

Maybe if you reply that this matters someone will bother to look at it.

**Comment by aaguiarz** [comment]
Maybe it's related to having Fiddler ON while developing?

https://github.com/IdentityServer/IdentityServer4/issues/1251#issuecomment-353660346

**Comment by aaguiarz** [comment]
Or this issue https://github.com/IdentityServer/IdentityServer4/issues/1251#issuecomment-363274043?

**Comment by kinetiq** [comment]
@aaguiarz  Thank you for the reply... These links are not related as far as I can tell.

I just double checked and confirmed that I do not have the fiddler chrome extension installed, nor did I run the fiddler desktop app any time this error occurred. 

As for the identity server issue you linked to, I did see that during my prior desperate flailing (along with every other related issue on github), however this one states that (a) this problem was specific to Google OAuth and I'm just using regular database users (b) the OP caused the issue by modifying app.UseCookiePolicy, and I am using the out-of-the-box configuration, which to me means that other people are probably experiencing this issue... You can see the entire configuration code, as well as a HAR, in the forum thread here:

https://community.auth0.com/t/asp-net-core-2-intermittent-correlation-failed-errors/11918

Hope that helps. Thanks so much!

**Comment by jerriep** [comment]
You may also look into this:
https://www.kevindockx.com/solving-correlation-failed-state-property-not-found-errors-openid-connect-middleware-asp-net-core/

If not exactly the same, you may try turning on detailed logging and stepping into the source like they did and see whether that enables you to better track it down?

**Comment by kinetiq** [comment]
@jerriep 

In this case there's probably a load balancer since this is hosted in Azure... It's worth a try.

Do you think they would dive into the HAR and resolve this if I signed up for a paid account? Trying to figure out if it's worth continuing. Thanks :)

**Comment by jerriep** [comment]
@kinetiq As I am not an Auth0 employee I am not really able to answer that question for you. To my understanding, paid customers have access to the support team (as opposed to just the community support website), so you likely will be better served if you have a paid account. 

But I am honestly not in a position to make promises to you as to whether getting a paid account will resolve your support issues. Best for someone from Auth0 to answer that.

**Comment by aaguiarz** [comment]
@kinetiq We looked at the HAR file, but it did not help. 

If you have a paid account you can submit support tickets, and have an SLA. That does not mean they'll be able to reproduce/understand/tell you how to fix the issue.

The way the login flow works is that when you get redirected to the Auth0 login page, ASP.NET sends a `state` parameter as part of the URL. In the callback, you receive the same `state`, and ASP.NET compares that the `state` it sent to `/authorize` is the same that was received in the callback.

My guess it that for whatever reason the place where ASP.NET stored the `state` does not have it anymore when you continue the flow after the inactivity period.

The trick described here could work https://github.com/IdentityServer/IdentityServer4/issues/720#issuecomment-372768518. Basically, when you get that error, you get redirected again to the `/authorize` page, with a new `state` parameter and complete the login flow.

One question, in the community forum you say "To reproduce this, when I go to my site after several hours (maybe a whole day?) of inactivity, It shows the “you last logged in with…” dialog, and then when I click my email address, it crashes". How does it show "last logged in with"? That's Auth0's page, right? How do you get redirected to that page? Clicking "Login"? Other way?

**Comment by jerriep** [comment]
@kinetiq I would also suggest you turn on **very detailed** logging for your ASP.NET Core app and see whether anything in the logs point out the possible culprit.

Also, have you asked on https://github.com/aspnet/security regarding this?

**Comment by jerriep** [comment]
Also, have a look at the [Data Protection configuration docs](https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.1&tabs=aspnetcore2x). My suspicion is that the cause of this has something to do with the data protection APIs not being able to work with that `state` parameter correctly

**Comment by kinetiq** [comment]
@BrianVallelunga I'm wondering what your hosting situation is... I'm using an Azure App Service.  You don't happen to be on that as well, do you?

**Comment by kinetiq** [comment]
@jerriep  I have not asked over there yet, that's a good idea.  I will turn on the more detailed logging and see if that surfaces anything :)

**Comment by aaguiarz** [comment]
@kinetiq the 'Last Logged In With' is a Lock feature, but I wonder what triggers it. You need to redirect to the Auth0 login page in order for it to be displayed, right? How do you land in that page after some time of inactivity?

The HAR file of a successful login could help, yes :).

Thanks

**Comment by kinetiq** [comment]
@aaguiarz This zip contains both the working and non-working HAR files, for anyone who might benefit from them.

[HARs.zip](https://github.com/auth0-samples/auth0-aspnetcore-mvc-samples/files/2102550/HARs.zip)

To your question about what redirects to Lock after inactivity... I've just been through my project, and this redirect is likely happening in the HomeController's index action, where I have some code like this:

        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
                return RedirectToAction("Login", "Account");

           // ... redirect users to other places based on their role ..
        }

This method does not require authentication, so maybe I'm simply handling that wrong and I can fix the whole problem by putting an [Authorize] attribute on there?? I'm still not sure what the mechanics are here. 

The login method is boilerplate, right from the quickstart, as far as I can tell:

        public async Task Login(string returnUrl = "/")
        {
            await HttpContext.ChallengeAsync("Auth0", new AuthenticationProperties() { RedirectUri = returnUrl });
        }
 
I also found a lead on another case where someone solved this by putting the key store into blob storage, which I like better than file system, since that seems like it would still have weaknesses in load balanced scenarios: https://stackoverflow.com/questions/50124498/correlation-failed-at-microsoft-aspnetcore-authentication-remoteauthenticationh

**Comment by aaguiarz** [comment]
@kinetiq The HAR did not help much.

If the code in `Index()` is executed is because the page was refreshed, right? How does that happen?

In any case, if the page is refreshed and the user is not authenticated (I assume because the ASP.NET session is set to a shorter period of time), then it should redirect to the Auth0 login page.

**Comment by kinetiq** [comment]
@aaguiarz It happens if I'm logged in, then I close my browser. The next day, I open the browser and type in my domain name. 

HomeController/Index runs in that case, and because the user is not authenticated, you can see in the code above that they are redirected to Login/Index, which invokes Lock by calling HttpContext.ChallengeAsync(..). This, for whatever reason, sometimes results in the option to select my email address to continue, which sometimes fails.

Is browsing to an action that requires authentication different than being redirected in code to the Login action? I think when I wrote this I must have made the assumption that these two things would be functionally identical... It sounds like I just require auth on that action, but at this point I feel like I need to understand how it works :)

**Comment by jerriep** [comment]
> Is browsing to an action that requires authentication different than being redirected in code to the Login action?

I cannot see that that would make *any* difference. I do not think that is the issue.

**Comment by aparent-emgs** [comment]
@kinetiq Sorry to bring this back up, but did you ever solve this issue? I'm having similar problems, also only in Chrome.

**Comment by kinetiq** [comment]
@aparent-emgs Okay, if I recall correctly this issue is actually caused by a stale login page. That can happen in two ways, one of which is sneaky and eluded me for awhile:

- Letting the login page sit there for too long before logging in
- Using the back button or bookmarks to get to a cached login page 

Once I fully understood the problem, which took quite some time, I added this to my auth0 config at the bottom of the OpenIdConnectEvents area, right after the OnRedirectToIdentityProviderForSignOut func...

```
                        // handle correlation failed errors caused by stale lock login pages.
                        OnRemoteFailure = (context) =>
                        {
                            if (context.Failure.Message == "Correlation failed.")
                            {
                                // [ log error ]
                                context.HandleResponse();
                                context.Response.Redirect("/Account/CorrelationFailed");
                            }

                            return Task.CompletedTask;
                        }
```

This causes users failing in this way to redirect to a partial  view, where I say something like: "There was a problem logging you in. Click here to try again." and there's a little collapsible more info section that explains how this might have been caused by using an old login page:

```
                <b>This usually happens when you try to use an old login page.</b> For security reasons, login pages expire after 15 minutes.<br />
                You can also end up with a stale login page if use the back button to find a login page created in the past, or if you bookmark the login page.<br />
```

Hope that saves you a lot of work...

**Comment by aparent-emgs** [comment]
Thanks a lot for the answer!

I actually found my specific problem a little after posting here, and it's unrelated. I'll post it here in case somebody stumbles across this thread:

https://devblogs.microsoft.com/aspnet/upcoming-samesite-cookie-changes-in-asp-net-and-asp-net-core/

Basically it seems Chrome is changing the standard of the "SameSite" property of cookies to enforce it to be set to "Lax", if I understand correctly. By default, when the OIDC middleware middle generates its correlation cookie (and nonce) cookies, it sets the "SameSite" property to "None". According to the article, it seems this is handled in some way AspNetCore 3.0, but my project is still in 2.2, so I still neede a way to fix it, so this is what I did in my configuration:

.AddOpenIdConnect(options =>
{
    // Other lines were omitted, only these two were useful to fix my problem

    options.NonceCookie.SameSite = SameSiteMode.Lax
    options.CorrelationCookie.SameSite = SameSiteMode.Lax

});
I don't know that it affects the behavior on other browsers... I tested after that in Chrome, Firefox and Edge with no issues.

**Comment by kinetiq** [comment]
Wow, what version of Chrome are you seeing this on? 

I do know SameSite changes are coming down the pipe, but I thought that was all somehow handled at the API level.

**Comment by aparent-emgs** [comment]
I'm using Version 80.0.3987.132. The article says it was scheduled to be released in version 80, which came out recently in the last weeks, I think.

But yea, it could also be I should just update the version of AspNetCore I use. I might try that, now that I think of it. Hadn't thought of that being a possible fix... eheh

**Comment by aparent-emgs** [comment]
An important detail I omitted though, I was only getting my issue when testing locally on my machine with everything hosted under http://localhost. It didn't happen when I had the application hosted elsewhere.

**Comment by kinetiq** [comment]
@aparent-emgs  Well guess what? Today I'm getting Correlation Failed on my dev machine, and I can't do any work in Chrome. Firefox works. I have a ticket open with Auth0. Any workaround yet?

**Comment by aparent-emgs** [comment]
I fixed mine right now by disabling #same-site-by-default-cookies in chrome://flags

**Comment by kinetiq** [comment]
@aparent-emgs Cool. Well, I've got a ticket open with Auth0 and I referenced this convo. Let's see what they say.

**Comment by The-Running-Dev** [comment]
So this is what fixed it for me when running over HTTPs.

in ConfigureServices
```
            services.Configure<CookiePolicyOptions>(options =>
            {
                options.MinimumSameSitePolicy = SameSiteMode.None;
                options.Secure = CookieSecurePolicy.Always;
            });
```

then in AddOpenIdConnect, set the same site the same as own cookie.
```
                services.AddAuthentication()....
                .AddOpenIdConnect(settings.Auth0.ClaimsIssuer, options =>
                {
                    options.NonceCookie.SameSite = SameSiteMode.None;
                    options.CorrelationCookie.SameSite = SameSiteMode.None;
```

And finally, UseCookiePolicty() before UseCookiePolicy():
```
app.UseCookiePolicy();
app.UseHttpsRedirection();
```

**Comment by kinetiq** [comment]
@The-Running-Dev  Thanks for the  heads up on that possible solution! I'm going to make sure the Auth0 people see this.

**Comment by kinetiq** [comment]
One dev on my team had a flare-up of this project today, again, only on Chrome. We changed our dev environment to use SSL, which is quite easy now, and that knocked it out with no problem.

-
