### ISSUE TITLE
ASP.Net Core 2.1 support?

### ISSUE THREAD

**Issue by BenHayat** [auth0-samples/auth0-aspnetcore-mvc-samples#37]
Hi;

When will you upgrade the samples and docs to the new version of .Net Core 2.1?
Thanks!

..Ben

**Comment by jerriep** [comment]
There are PRs that I am waiting for to be merged:
https://github.com/auth0/docs/pull/6237

There are however no major changes (nothing like from 1.1 to 2.0), so you can follow the quickstarts with 2.1 and it will work as well.

**Comment by BenHayat** [comment]
Thanks!
