### ISSUE TITLE
Certified is expired

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-aspnetcore-mvc-samples#42]
When executing the sample code, is shown that the certified is currently expired:

![image](https://user-images.githubusercontent.com/15782359/44063194-0505dc72-9f36-11e8-9eed-8d17ddf82621.png)

**Comment by jerriep** [comment]
Please see https://www.hanselman.com/blog/DevelopingLocallyWithASPNETCoreUnderHTTPSSSLAndSelfSignedCerts.aspx
