### ISSUE TITLE
Document and provide workaround for WebKit issues

### ISSUE THREAD

**Issue by nicosabena** [auth0-samples/auth0-aspnetcore-mvc-samples#45]
WebKit in OS X Mojave and iOS 12 does not play well with cookies when using the default flow in the OpenIdConnect middleware (of `response_mode=form_post`), as the session cookie generated by the cookie middleware is not sent back to the application after is set. 
This is documented here:
https://community.auth0.com/t/authentication-broken-on-asp-net-core-and-safari-on-ios-12-mojave/16077/2

Workaround is configure the `response_type` and `response_mode` for a traditional authorization code flow (`response_type=code`) instead of the default hybrid, with the result in a redirect (`response_mode=query`):
```cs
.AddOpenIdConnect("Auth0", options => {
    // Other configuration options
    [...]
    // Set response type to code and response type to query
    // to avoid the default response_mode=form_post
    // which causes issues with Safari's handling of 
    // the Cookie middleware's default samesite=lax policy
    options.ResponseType = "code";
    options.ResponseMode = "query";
}
```

**Comment by pixelport** [comment]
Thanks for taking care of this. 
Note: Your workaround seems to lead to a redirect loop on Safari in OS X Mojave. Others seem to have the same problem: https://bugs.webkit.org/show_bug.cgi?id=188165#c22

**Comment by nicosabena** [comment]
Hi @pixelport . I wasn't able to see an issue with using the above workaround, but I'll keep trying. If you can provide a minimum reproducible sample or a .HAR file, that'd be great.

**Comment by nicosabena** [comment]
@pixelport I finally found out that the WebKit issue persists even if preventing `response_mode=form_post` when there's a POST in the authentication flow (like sending credentials to the identity provider).
I wrote about a new workaround at https://community.auth0.com/t/authentication-broken-on-asp-net-core-and-safari-on-ios-12-mojave-take-2/19104
