### ISSUE TITLE
Add code showing how to handle remote auth errors

### ISSUE THREAD

**Issue by nicosabena** [auth0-samples/auth0-aspnetcore-mvc-samples#46]
Show how to make a basic error handler for a better user experience when the correlation id is not found or is expired:

```
options.Events.OnRemoteFailure = (context) =>
    {
        if (context.Failure.Message == "Correlation failed.") {
            [...] // log failure
            context.HandleResponse();
            context.Response.Redirect("/Account/CorrelationFailed");
        }
        return Task.CompletedTask;
    };
```

This could probably be made even more generic to handle all possible errors.

**Comment by kinetiq** [comment]
For what it's worth, just tested this and it works great.  This problem has been bugging me for months, so this is fantastic.
