### ISSUE TITLE
Update sample to .NET Core v3.1? 

### ISSUE THREAD

**Issue by SeanKilleen** [auth0-samples/auth0-aspnetcore-mvc-samples#52]
Hi all,

On the quickstart page for .NET Core MVC Login: 

> ![image](https://user-images.githubusercontent.com/2148318/73129944-ed8c0700-3fbc-11ea-9f4e-5e38072849dc.png)

When I click the download link, I receive a file called `aspnet-core-3-01-login.zip`.

However, the project that is generated appears to target `netcoreapp2.1`.

I'm going to fork & do a PR real quick because I think we'll be able to make quick work of it.

However, wanted to start this issue as a heads up / discussion so you can talk me down if it's not the right path. :)

**Comment by damieng** [comment]
Thanks for fixing this! #53
