### ISSUE TITLE
Refactoring the application and doc to use minimal hosting model

### ISSUE THREAD

**Issue by LayersOfAbstraction** [auth0-samples/auth0-aspnetcore-mvc-samples#79]
Hi just wondering if you would consider me contributing a refractor for your application and docs to use ASP.NET 6's minimal code hosting model, please?

It would mean the logic is contained in that one Program.cs file and would mean one less file.

**Comment by frederikprijck** [comment]
Thanks for proposing this. Can you elaborate why you believe it would be a good idea to do so ?

**Comment by LayersOfAbstraction** [comment]
Besides what I already stated, it's only a matter of time until the .NET team do away with the startup.cs file or limit/end support for it as it would mean one less file for them to maintain in future versions of .NET. I think if we move on to this at some point it may make the overall quickstart easier to maintain.

**Comment by frederikprijck** [comment]
As long as you are saying to merge Program.cs and Startup.cs, I am down for the changes.

However, it would also mean the changes need to be reflected here: https://github.com/auth0/docs/tree/master/articles/quickstart/webapp/aspnet-core

On top of that, I believe we should be consistent, so we should also patch https://github.com/auth0-samples/auth0-aspnetcore-webapi-samples and correspondingly https://github.com/auth0/docs/tree/master/articles/quickstart/backend/aspnet-core-webapi

Not saying I expect you to do these, just calling out the fact that the effort is not low and our priorities ourselves are currently elsewhere.

**Comment by LayersOfAbstraction** [comment]
That's ok I will try and do these one at a time. I'll start making a branch for the quickstart app this week and then when it looks good enough to you I will try to make a branch in the docs repo and reverse-engineer it a bit. Not expecting any successful PR until I've finished all PRs for the docs and each of their respective ASP.NET/Web API quickstart apps. Thanks.

**Comment by LayersOfAbstraction** [comment]
All done with the draft PRs. Not making any more for now.

**Comment by frederikprijck** [comment]
Thanks for all the work here @LayersOfAbstraction ! Appreciate it!

**Comment by frederikprijck** [comment]
Closing as everything is merged, thanks again for all the effort here 🚀

**Comment by LayersOfAbstraction** [comment]
> Closing as everything is merged, thanks again for all the effort here 🚀

Thank you! I didn't expect you to merge so quickly. Look if you have a LinkedIn profile it would be great to have an endorsement and a mention from you on my profile. I don't think you use LinkedIn though so it is fine. I was just asking.
