### ISSUE TITLE
Production environment error (working in localhost)

### ISSUE THREAD

**Issue by juanjoserodriguezmagro** [auth0-samples/auth0-aspnetcore-mvc-samples#80]
Hello,

I have published this mvc sample (using my Auth0 ClientId and Domain credentials) in a production environment.

On localhost I can see the login page, but on production environment I get an error.

Do we know why? Thanks.

An unhandled exception occurred while processing the request.
SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)

**Comment by frederikprijck** [comment]
Hey, not sure. can you ping your auth0 domain if you connect to your production server?

**Comment by juanjoserodriguezmagro** [comment]
I am reading about "IdentityModelEventSource.ShowPII = true;". It does not work.
I can not find posts about Auth0 NET 6 MVC in production environments. Using IONOS like hosting.

**Comment by frederikprijck** [comment]
We can't really help with hosting issues. I would recommend verifying you can access your Auth0 domain from your production server. It's not uncommon that network errors can cause issues, but there are beyond our SDK.
